# Generated by Django 4.1.3 on 2022-11-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_status_type_remove_task_deadline_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.status', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
