# Generated by Django 4.1.3 on 2022-11-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_type_task_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_set', to='webapp.type', verbose_name='Тип'),
        ),
    ]
