# Generated by Django 4.1.3 on 2022-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_rename_type_task_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('date_started', models.DateField(verbose_name='Дата Начала')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата Окончания')),
            ],
        ),
    ]
