# Generated by Django 4.1.3 on 2022-12-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_users_in_project', 'Добавить юзера в проект')]},
        ),
    ]
